In [ ]:
#61  Exercise 61:Average
a=[]
input_num=0
sum=0


while True:
    input_num=int(input())
       
    if input_num is 0:
        break
    a.append(input_num)
    
for i in a:
    sum += i

print(sum/len(a))

In [ ]:
#62

num=0.0
while True:
    num=float(input('현재가격 : '))
    print("할인가격 :",num, "정상가격 :",round(num*1.6,2))

In [7]:
#63

print('Cel    Faren')
for i in range(1,101):
    print(i,'   ',round((i-32)/1.8,2))

Cel    Faren
1     -17.22
2     -16.67
3     -16.11
4     -15.56
5     -15.0
6     -14.44
7     -13.89
8     -13.33
9     -12.78
10     -12.22
11     -11.67
12     -11.11
13     -10.56
14     -10.0
15     -9.44
16     -8.89
17     -8.33
18     -7.78
19     -7.22
20     -6.67
21     -6.11
22     -5.56
23     -5.0
24     -4.44
25     -3.89
26     -3.33
27     -2.78
28     -2.22
29     -1.67
30     -1.11
31     -0.56
32     0.0
33     0.56
34     1.11
35     1.67
36     2.22
37     2.78
38     3.33
39     3.89
40     4.44
41     5.0
42     5.56
43     6.11
44     6.67
45     7.22
46     7.78
47     8.33
48     8.89
49     9.44
50     10.0
51     10.56
52     11.11
53     11.67
54     12.22
55     12.78
56     13.33
57     13.89
58     14.44
59     15.0
60     15.56
61     16.11
62     16.67
63     17.22
64     17.78
65     18.33
66     18.89
67     19.44
68     20.0
69     20.56
70     21.11
71     21.67
72     22.22
73     22.78
74     23.33
75     23.89
76     24.44
77     25.0
78     25.56
79     26.11
80     26.67
81     27.22
82     27.78
83     28.33
84     28.89
85     29.44
86     30.0
87     30.56
88     31.11
89     31.67
90     32.22
91     32.78
92     33.33
93     33.89
94     34.44
95     35.0
96     35.56
97     36.11
98     36.67
99     37.22
100     37.78

In [56]:
#80
import random

k=0
avg=0
for k in range(0,10):
    num=5
    h=0   #h=1
    t=0   #t=0
    cnt=[]
    str=[]
    while True:
        num=random.randrange(0,2)
        cnt.append(num)
        if num:
            h+=1
            t=0
        else:
            t+=1
            h=0

        if h==3 or t==3:
            break

    for j in cnt:
        if cnt[j]:
            str.append('H')
        else:
            str.append('T')
    
    avg+=len(str)
    print(str,'(',len(str),'flips',')')
k+=1

print('On average, ',avg/10, 'flips were needed')

['T', 'H', 'H', 'H'] ( 4 flips )
['T', 'T', 'T', 'T', 'T', 'T'] ( 6 flips )
['T', 'T', 'T'] ( 3 flips )
['H', 'H', 'H', 'H', 'H'] ( 5 flips )
['T', 'T', 'T'] ( 3 flips )
['T', 'H', 'T', 'T', 'H', 'T', 'H', 'H', 'H'] ( 9 flips )
['H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'] ( 12 flips )
['T', 'H', 'H', 'T', 'H', 'H', 'H'] ( 7 flips )
['T', 'H', 'T', 'H', 'H', 'H'] ( 6 flips )
['T', 'H', 'H', 'H'] ( 4 flips )
On average,  5.9 flips were needed